### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by nudtchengqing** [nmarinsek/burst_detection#2]
When d or is large, the program explodes"RuntimeWarning: invalid value encountered in double_scalars "

i think is the problem of fit function .

**Comment by nmarinsek** [comment]
Hi Jack, 

I’m sorry for taking so long to respond. I think I may have fixed the issue and I updated the package (burst_detection_0.1.3). The issue I ran into was that the computations in the fit function needed a higher level of precision, so I had to use the mpmath instead of numpy. 

Thank you for bringing the error to my attention. Let me know if the most recent package works for you. 

Best,
Nikki
